normalization.js, package-lock.json, package.json
To enable this API to be used for the creation or validation of Igbo language datasets, this project needs to be able to normalize Igbo text.
The code found in this branch is directly inspired by [goodyduru/igbo-text](https://github.com/goodyduru/igbo-text).
=> Create normalization functions

README.md, controllers/words.js, dictionaries/seed.js, middleware/logger.js, routers/index.js, routers/router.js, routers/testRouter.js, server.js, shared/constants/diacriticCodes.js, tests/__mocks__/data.mock.json, tests/database.test.js, tests/parse.test.js, tests/shared/commands.js
Now there are two different routes:
```
api/v1/search/words // JSON data
api/v1/test/words // MongoDB data
```
After populating the database, developers can use `api/v1/test/words` to search for words.
Closes #47
=> GET words routes

README.md, routers/router.js, routers/testRouter.js, server.js, tests/shared/commands.js, tests/shared/constants.js
The express routes have been switched. Now the routes are as follows:
`api/v1/search/words` returns word data from the local MongoDB database
`api/v1/test/words` returns wor data from the JSON dictionary
Closes #51
=> Switch Express Routes

README.md, controllers/words.js, tests/database.test.js
If a user searches for an English term, the API will first treat that provided keyword as an Igbo word and search the database.
If there's no word responses, then the backend will search the database again but this time treating the provided keyword as an English term.
Closes #7
=> Use English to Search for Igbo Terms

package.json
In order for Heroku to have access to `babel`, it needs to be under `dependencies` instead of `devDependencies`
=> Use babel in dependencies

.gitignore
Built files from the `gatsby-dev` branch might spill into other branches. To ensure that those files don't accidentally get included in PRs the `.gitignore` file is updated to ignore `build/` and `public/`
=> Ignore build and public files

package.json, src/controllers/phrases.js, src/controllers/words.js, tests/api-mongo.test.js, yarn.lock
The API now checks how similar a provided English term is to the matched definitions so that it can order the most relevant Igbo words for the user.
=> Order relevant words

src/models/Example.js, src/models/Phrase.js, src/models/Word.js, src/models/plugins/index.js, tests/api-mongo.test.js
Now the API will return "cleaner" objects where there's no `__v` key and the `_id` has been replaced with `id`.
Close #79
=> Remove _id and __v keys

README.md, package.json, src/config.js, src/routers/router.js, src/routers/testRouter.js, src/server.js, yarn.lock
Using swagger.io, I have added documentation for this API. Now we can document the API from our comments and see changes reflected at `http://localhost:8080/docs/`.  
This addresses issue #92.
This is how the docs look.
=> Added documentation page for API

src/controllers/exampleSuggestions.js, src/controllers/wordSuggestions.js, src/routers/editRouter.js, tests/__mocks__/suggestions.js, tests/exampleSuggestions.test.js, tests/shared/commands.js, tests/wordSuggestions.test.js
Create /GET routes for `WordSuggestion` and `ExampleSuggestion` documents. There's also the ability to search for individual `WordSuggestion` and `ExampleSuggestion` documents with the `/:id` path
Closes #121
=> Igbo api 121 - GET routes word example suggestions

src/controllers/exampleSuggestions.js, src/controllers/genericWords.js, src/controllers/utils/index.js, src/controllers/wordSuggestions.js, src/controllers/words.js, src/server.js, tests/api-mongo.test.js, tests/exampleSuggestions.test.js, tests/genericWords.test.js, tests/shared/utils.js, tests/wordSuggestions.test.js
In order for the frontend to know what the total number of words or other documents exist in the database, the `Content-Range` header needs to be defined.
The API can now use the `range` query to paginate through response bodies.
=> Igbo api - supply content range header

src/controllers/exampleSuggestions.js, src/controllers/genericWords.js, src/controllers/utils/index.js, src/controllers/wordSuggestions.js, src/controllers/words.js, tests/exampleSuggestions.test.js, tests/genericWords.test.js, tests/wordSuggestions.test.js
The `WordSuggestion`, `ExampleSuggestion`, and `GenericWord` get routes can now take the `keyword` query to be able to  use the document's `word`, `igbo`, and `english` keys for search
Closes #95 
Closes #130
=> Igbo api 130/Search word and example suggestions

README.md, src/controllers/examples.js, src/routers/router.js, tests/api-mongo.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/genericWords.test.js, tests/shared/commands.js, tests/wordSuggestions.test.js
This PR creates a new route `api/v1/examples` that allows developers to see the examples offered in the API
Closes #142
=> Igbo api 142/get examples

src/controllers/examples.js, src/controllers/words.js, src/routers/router.js, tests/__mocks__/documentData.js, tests/api-mongo.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/shared/commands.js, tests/wordSuggestions.test.js
Exposes two new routes that allow for a **merger** to create a new `Word` or `Example` document in the database.
Closes #147
=> Igbo api 147/post words examples

src/controllers/exampleSuggestions.js, src/controllers/examples.js, src/controllers/genericWords.js, src/controllers/wordSuggestions.js, src/controllers/words.js, src/routers/router.js, tests/api-mongo.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/genericWords.test.js, tests/shared/commands.js, tests/shared/constants.js, tests/wordSuggestions.test.js
Consumers of the API will be able to grab a single word or example by using the following routes:
`api/v1/words/:id`
`api/v1/examples/:id`
Closes #93
=> Igbo api 93/get words with Id

src/controllers/genericWords.js, src/routers/editRouter.js, src/routers/router.js, tests/__mocks__/documentData.js, tests/genericWords.test.js, tests/shared/commands.js
When a PUT request is made at the `api/v1/edit/genericWords/:id` endpoint, a `GenericWord` document can be updated
Closes #153
=> Igbo api 153/put generic words

src/controllers/exampleSuggestions.js, src/controllers/examples.js, src/controllers/genericWords.js, src/controllers/utils/index.js, src/controllers/wordSuggestions.js, src/controllers/words.js, src/models/ExampleSuggestion.js, src/models/GenericWord.js, src/models/WordSuggestion.js, tests/__mocks__/documentData.js, tests/api-mongo.test.js, tests/examples.test.js
The POST routes for `Words` and `Examples` are now updated requiring the data that provided needs to be an either pre-existing `WordSuggestion` or `ExampleSuggestion` document
=> Merge Words and Examples

src/controllers/genericWords.js, src/models/ExampleSuggestion.js, src/models/GenericWord.js, src/models/WordSuggestion.js
This updates the shape of the `WordSuggestion`, `ExampleSuggestion`, and `GenericWord` collection documents so that it's easier to keep track of updated data.
Also, `ig-en_normalized_expanded.json` was accidentally overwritten in a past PR. The correct data is restored.
Closes #149
=> Change schemas for suggestions and generic documents

src/controllers/exampleSuggestions.js, src/controllers/genericWords.js, src/controllers/wordSuggestions.js, tests/__mocks__/documentData.js, tests/api-mongo.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/genericWords.test.js, tests/shared/utils.js, tests/wordSuggestions.test.js
Responses for `WordSuggestion`, `ExampleSuggestion`, and `GenericWord` documents will first be sorted by the number of approvals they have. This will make it easier to see the most important documents to be reviewed.
Closes #178
=> Igbo api 178/sort suggestions and generic documents

src/controllers/examples.js, src/controllers/genericWords.js, src/controllers/wordSuggestions.js
If a list of definitions for any suggestion document is passed to the API as a comma delimited string, then the API should be able to parse that string and convert it into an array of definitions.
=> Handle string representation of definitions

src/controllers/wordSuggestions.js, src/routers/editorRouter.js, tests/__mocks__/documentData.js, tests/shared/commands.js, tests/wordSuggestions.test.js
This exposes a new DELETE route for `WordSuggestion` documents with the route `api/v1/wordSuggestions/:id`
=> Igbo api 166/delete word suggestions

package.json, src/controllers/exampleSuggestions.js, src/controllers/examples.js, src/controllers/wordSuggestions.js, src/controllers/words.js, src/models/ExampleSuggestion.js, src/models/WordSuggestion.js, src/routers/editorRouter.js, swagger.json, tests/__mocks__/documentData.js, tests/api-json.test.js, tests/api-mongo.test.js, tests/examples.test.js, tests/genericWords.test.js, tests/shared/constants.js
The merge routes weren't actually converting `WordSuggestion`, `ExampleSuggestion`, and `GenericWord` documents into either `Word` or `Example` documents. This PR fixes this issue alongside introduces more tests.
=> Update Merge routes

package.json, src/controllers/exampleSuggestions.js, src/controllers/examples.js, src/controllers/genericWords.js, src/controllers/utils/index.js, src/controllers/wordSuggestions.js, src/controllers/words.js, swagger.json, tests/api-json.test.js, tests/api-mongo.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/genericWords.test.js, tests/parse.test.js, tests/shared/constants.js, tests/shared/utils.js, tests/wordSuggestions.test.js
No longer handles the `pageQuery`. Instead, the functionality for the `range` query is expanded. Now a consumer of the API is able to specify how many items (within a range) they want to get back from the database. The max number of documents that can be returned from the database is 25.
Closes #201
=> Igbo api 201/per page query

tests/api-mongo.test.js
`skip` was applied to the flaky Regex test to allow the test suite to pass. This was a temporary change in order to let the other non-flaky tests to pass consistently.
I think this test just needed a longer timeout in order to complete.
Closes #196
=> Remove skip flag from regex test

src/controllers/utils/index.js, src/controllers/words.js
The API was forcing sorting by falling back on sorting words by their ids in ascending order. This caused the search results to be unexpected for end users. This change will lead to a more accurate search.
Closes #216
=> Stop forcing sorting

src/controllers/wordSuggestions.js, tests/exampleSuggestions.test.js
One of the tests from #234 didn't properly check whether an `exampleSuggestion` gets nested as expected.
=> Update wrong test

src/controllers/genericWords.js, src/controllers/utils/index.js, src/controllers/utils/queries.js, tests/api-mongo.test.js, tests/genericWords.test.js
One of the genericWords tests seemed to be flaky. But after taking a closer it looks, it actually was failing because the expected filter functionality wasn't working.
The "flaky" test should be more stable.
=> Filter searches through definitions of generic words

src/models/ExampleSuggestion.js, src/models/GenericWord.js, src/models/WordSuggestion.js, src/models/plugins/index.js, tests/exampleSuggestions.test.js, tests/genericWords.test.js, tests/wordSuggestions.test.js
Documents have an `updatedOn` field that didn't accurately capture when a `wordSuggestion`, `exampleSuggestion`, or even a `genericWord` document was updated in the database.
This PR fixes that problem by defining the pre `save` hook that gets called whenever a document is about to get saved to the database.
Closes #228
=> Update the updatedOn field for documents

cypress/integration/example.spec.js, cypress/integration/word.spec.js, package.json, src/API.js, src/components/Email.js, src/forms/AddExample.js, src/forms/AddWord.js, src/pages/search.js, src/pages/word.js, src/styles/tailwind.css, src/utils/parseQueries.js, yarn.lock
The `input` elements are now `textarea` elements to make it easier for users to edit long definitions.
There's also a new `Email` component responsible for rendering the email field within both the `addWord` and `addExample` components.
Closes #223 
Closes #219
=> Igbo api 223/textareas for definitions

scripts/sync.sh, src/controllers/exampleSuggestions.js, src/controllers/examples.js, src/controllers/genericWords.js, src/controllers/utils/index.js, src/controllers/wordSuggestions.js, src/controllers/words.js, src/shared/constants/sortingDirections.js, tests/api-mongo.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/genericWords.test.js, tests/shared/utils.js, tests/wordSuggestions.test.js
The API was too lenient with incorrectly formatted queries. If a consumer of the API accidentally forgot to close the `range` query with the `]` character, the API would handle that for the consumer without notifying them they provided an incorrectly formatted query.
Also, the `sync.sh` script tar file naming convention had days before months. The new tar file names will have months before days.
Now the API will return an error message if the consumer doesn't follow the expected query syntax. 
Closes #239
=> Igbo api 239/invalid queries

src/controllers/words.js, src/shared/constants/suggestionTypes.js, tests/api-mongo.test.js, tests/auth.test.js, tests/editing-flow.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/shared/commands.js
This PR:
* Removes the concept of `SuggestionTypes.WORD_SUGGESTIONS` and `SuggestionTypes.GENERIC_WORDS`
* Updates the test suite to only expect a `wordSuggestion`, `genericWord`, or `exampleSuggestion` id passed in as the firsrt argument of `createWord` or `createExample`
Closes #244 
Closes #240
=> Igbo api 244/remove doc type

src/controllers/genericWords.js
Whenever a user makes a 'POST' network request to `api/v1/genericWords` to seed the database with some genericWords, an `ERR_EMPTY_RESPONSE` response header would be returned. This would break out testing environments.
=>  Return createGenericWords promises

src/controllers/words.js, tests/api-mongo.test.js
The `mergedBy` field in nested exampleSuggestions is null once actually merged. This is a bug since the `uid` of the user that merged the exampleSuggestion should be listed there.
This PR fixes this bug.
=> Assign mergedBy field for nested examples

src/controllers/email.js, src/services/sendEmail.js
* Changes the automated message time from Mondays at 1AM PST to Mondays at 6AM PST
* The `from` field is updated to now include an object that includes the `from` email and name
* Uses `personalizations` field to simulate blind carbon copied (BCC) emails
=> Hide recipient list for all emails and change automated email times

src/config.js, src/server.js
To protect the editor routes, the CORS rules are more strict to expect requests only coming from the Igbo API homepage and Nkowaokwu
=> Update CORS rules

src/controllers/exampleSuggestions.js, src/controllers/genericWords.js, src/controllers/wordSuggestions.js, src/middleware/authentication.js, tests/__mocks__/documentData.js, tests/api-mongo.test.js, tests/auth.test.js, tests/editing-flow.test.js, tests/exampleSuggestions.test.js, tests/examples.test.js, tests/genericWords.test.js, tests/shared/commands.js, tests/wordSuggestions.test.js
The API will now return a sorted list of wordSuggestions, exampleSuggestions, and wordSuggestions by number approvals in descending order
This PR also:
* Updates the API of test commands to reduce repeated logic
* Removes `skip` suffix for two tests
* Closes #266
=> Sort documents

src/controllers/exampleSuggestions.js, src/controllers/genericWords.js, src/controllers/utils/index.js, src/controllers/wordSuggestions.js
Sorting Suggestion type documents will now rely on the `updatedOn` and the `approvals` keys.
=> Change sorting logic to rely on updated on and approvals

migrations/20201206042142-add-accented-field.js, package.json, src/controllers/utils/buildDocs.js, src/models/Example.js, src/models/Word.js, src/models/plugins/index.js, tests/api-mongo.test.js, tests/examples.test.js, tests/shared/constants.js, yarn.lock
The Igbo language doesn't include accent marks in everyday writing. However, the accent marks are helpful for denoted tone. There's now a new `accented` field that lives on words and examples that will include tone markings.
The database migration couldn't accept custom functions and references to documents, so it was impossible to remove the accent marks for every document in the database migration up function. To get around this problem, there are `find` and `findOne` hooks for words and examples that will remove the accent marks from the `word` and `igbo` fields before it gets sent back to the client.
This means, in the database, the `word` and `igbo` fields still have accent marks, but they get processed before they reach the client.
=> Change word example schemas

src/controllers/utils/index.js, src/controllers/utils/queries.js, src/controllers/words.js, src/shared/utils/createRegExp.js, swagger.json, tests/api-mongo.test.js
When the `strict` query is provided with the value of `'true'` the API will perform a whole word match with the generated regex.
=> Strict search

src/controllers/exampleSuggestions.js, src/controllers/examples.js, src/controllers/genericWords.js, src/controllers/users.js, src/controllers/utils/index.js, src/controllers/wordSuggestions.js, src/controllers/words.js, src/dictionaries/seed.js, src/middleware/authorization.js, src/middleware/errorHandler.js, src/middleware/validId.js, src/routers/editorRouter.js, src/server.js, tests/api-json.test.js, tests/api-mongo.test.js, tests/cron-jobs.test.js, tests/editing-flow.test.js, tests/exampleSuggestions.test.js, tests/genericWords.test.js, tests/shared/commands.js, tests/shared/utils.js, tests/wordSuggestions.test.js
The API shouldn't have the ability to delete word documents at this moment. Instead, if a word document should be "deleted" it should be combined into another word document. This approach is better since it preserves the soon-to-be-deleted word's information.
This PR:
* Updates existing tests to handle new middleware
* Creates a new Express error handler middleware
Closes #294
=> Combine deleted words

docker-compose.yml, src/controllers/genericWords.js, src/dictionaries/seed.js, tests/api-json.test.js, tests/shared/utils.js
Due to MongoDB Text Indexes not created properly while the server is up, the server needs to be restarted in order for the database to detect that new text indexes have been created.
Restarted the database to detect new text indexes is only necessary inside a Docker container since the Docker container doesn't recognize that the server needs to be restarted in order to see text indexes.
This PR checks to see if the server is running in a Docker container. If it is, then it will redirect the client back to the homepage of the API and then wait two seconds to close the instance of the server. Docker will automatically restart the server because of the docker-compose's `restart: always` option
=> Terminate server after seeding database so Docker can automatically restart the server container

src/controllers/wordSuggestions.js, src/controllers/words.js, tests/api-mongo.test.js
When a word document gets combined into another word document, it has essentially been deleted from the database. This leaves wordSuggestions with an existing `originalWordId` "orphaned" if their `originalWordId` was pointing to the recently deleted word document.
This PR adds the functionality of finding all wordSuggestions with their `originalWordId` pointing to the recently deleted word document and deleted those wordSuggestions.
**Note: This will delete all associated wordSuggestions, merged or not.**
=> Delete orphan word suggestions

src/config.js, src/pages/App.js, src/server.js, tailwind.config.js
Removing the open CORS policy for developments. This means if a developer wants to use the API right now, they would need to run the API locally or request access to the API by sending an email to igboapi@gmail.
This PR also:
* Purges unused CSS styles to make total bundle size smaller
=> Remove open CORS policy for production apps

src/pages/404.js, src/pages/components/Demo/Demo.js, src/pages/components/Navbar/Navbar.js, src/server.js, tests/homepage.test.js, tests/shared/commands.js
The homepage would automatically jump to the Try it Out section when the user first visits the site, which is really confusing.
This PR fixes that bug.
This PR also:
* Remove unit tests that test production code along with the command used in those tests
* Creates a new 404 Not Found
* Redirects users back to the homepage if they provide an invalid route
=> Land at the top of the page on first load

src/config.js, swagger.json
The docs in production are unable to make successful requests since it was making HTTP protocol requests instead of HTTPS.
=> Use HTTPS for docs when deployed

package.json, src/config.js, src/controllers/developers.js, src/middleware/validateApiKey.js, yarn.lock
To secret API tokens, the API is now using `bcrypt` for salting and hashing passwords.
=> Use bcrypt to salt and hash passwords

Dockerfile, src/config.js
When a new Docker container was created with this project's Docker file, the environment would automatically assume it's running in a testing environment by setting `NODE_ENV` to `test` in the Dockerfile.
However, the Dockerfile should be responsible for setting the environment variable. Instead, the application that creates the container with the Dockerfile should have the ability to set `NODE_ENV`. This PR changes the Dockerfile and `config.js` to make it possible to change `NODE_ENV` from outside the container.
=> Allow Docker consumers to change NODE_ENV variable

cypress/fixtures/example.json, src/pages/signup.js
The production API route (https://igboapi.com) was not getting used in production. Instead, it was falling back on the development route (http://localhost:8080)
Check the current environment the API is running and conditionally change the API routes.
=> Use window and process environment to switch to proper API URL

.github/workflows/backup.yml, .github/workflows/dockerize.yml, .github/workflows/integration.yml, .github/workflows/versioning.yml, commitlint.config.js, package.json, yarn.lock
To make this project's commit history easier to read and interpret for any contributing developer, the Igbo API will now start using [SemVer](https://semver.org/) for the package versioning and [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) which provides a set of rules for creating an explicit git history that follows SemVer
This means that **all** commits to this repo must follow the Conventional Commit syntax in order to be logged. There is a new CLI tool installed that will lint all commit messages, to make sure that they are properly formatted.
This PR:
* Adds names to all GitHub Action workflows
=> Use Semantic Versioning and Conventional Commits

tailwind.config.js
Checking whether Tailwind is in a production or development is done automatically by Tailwind, so there's no need for its config to explicitly make the check again
Remove the `enabled` field from the `purge` object so the responsibility of determining whether or not to purge styles will be 100% up to Tailwind
=> Remove the conditional purge check

.github/workflows/release.yml, package.json, src/controllers/words.js, tests/cypress/integration/client.test.js
The `dialects` query param was only working when a request was made searching for a word using the `keyword` query param. `dialects` should also work when an individual word document was requested when a request was made with the word document `id`
This PR also:
* Update the `client.test.js` file to reduce redudant code
* An initial attempt to start using `semantic-release`
=> Dialects for individual words

src/controllers/words.js
The `createWord` function that's used for populating the database didn't handle the `dialects` that came from the client side.
=> fix: handle dialects from client

migrations/20210325194345-add-central-igbo.js, package.json, src/controllers/utils/buildDocs.js, src/models/Word.js, tests/shared/constants.js
To keep track of a headword of an entry is in Central Igbo or not, a new `isCentralIgbo` in the word document. This key will not be exposed via the API since it's still experimental.
This PR also:
* Stops sending over `normalized` key since it's always empty. It might be completely deprecated and dropped from the database
=> Add Central Igbo

src/controllers/utils/buildDocs.js
If there is a case where there are two identical head words, MongoDB will then sort by the secondary `_id` field to make sure that the same sorted order is preserved upon each execution of grabbing words.
=> Ensure consistency sorting order for each get word execution

src/shared/constants/wordClass.js
The Igbo API can now support the new 'Name' `wordClass`
=> Name Word Class

src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/words.js, src/pages/components/Demo/Demo.js, swagger.json, tests/api-mongo.test.js, tests/shared/constants.js
Users were experiencing extremely long load times for requesting word documents that were at the end of the database (i.e. words that start with the letter 'w' would take a lot longer to be returned to the client compared to words starting with the letter 'a')
Originally, all words would unconditionally look up their associated example documents. But this would increase the look-up time for more word document requests. This PR creates a new `example` query param that allows clients to specify whether or not they want to also request the associated example documents.
This significantly increases performance - I ran tests locally I noticed that the original ~8s request time for 10 words dropped down to 80ms 😱
=> Examples Flag

src/controllers/utils/buildDocs.js, src/models/Word.js, swagger.json, tests/shared/constants.js
Each word document can have a pronunciation audio file associated with it. This PR exposes the `pronunciation` field that can contain an AWS S3 Bucket object URI that points to the audio pronunciation file.
This PR also:
* Updates the Swagger docs to better represents the shape of the Word schema
=> Expose Pronunciation Field

migrations/20210426171953-remove-normalized-field.js, src/models/Word.js
Word documents no longer need the `normalized` field, so this PR removes it.
Closes #354
=> fix: remove normalized field on word documents

src/dictionaries/seed.js, src/models/Word.js, tests/api-mongo.test.js
When a user searches for a word, the backend uses MongoDB text indexes to look at each Word document `word` and `variations` fields to see if they match the user's search query. This meant that users who would search for words in their own dialects wouldn't get as many results if the word in their dialect didn't exactly match the headword for a given document.
This PR extends the text indexes to look at all the nested dialect words. This means if a headword is `mmiri` but a nested dialect word is `mmili`, a user would be able to search with `mmili` and get the document with the headword `mmiri` as a result.
Closes #356
=> Search for Words by Dialects

migrations/20210814210437-pre-populate-dialects.js, src/controllers/words.js, src/dictionaries/seed.js
All the default values for a given word's dialect's `word` and `accented` fields are empty. We want to have the default value for nested dialect fields `word` and `accented` to have the same initial value as the head word's `accented` or `word` field.
This PR introduces a migration that will set all the nested `word` and `accented` fields within the `dialects` field for any word to the word's `accented` or `word` value.
=> Migrating database to have default dialects

migrations/20210820170937-merge-accented-and-word.js, migrations/20210820175620-merge-accented-and-example.js, package.json, src/controllers/utils/buildDocs.js, src/controllers/words.js, src/dictionaries/seed.js, src/models/Example.js, src/models/Word.js, src/models/plugins/index.js, swagger.json, tests/api-mongo.test.js, tests/examples.test.js, tests/shared/constants.js, yarn.lock
The `accented` field is no longer necessary since the `word` can handle diacritics. This PR removes the `accented` field and overwrites all `word` fields with the original `accented` field data.
This PR also:
* Remove the `remove-accents` npm package
=> Remove `accented` field from Words and Examples

migrations/20210822145619-change-central-to-standard.js, src/controllers/utils/buildDocs.js, src/models/Word.js, swagger.json, tests/shared/constants.js
To better represent the type of data that's being stored in our database we want to change the `isCentralIgbo` field to `isStandardIgbo`.
Closes #390
=> feat: change Central Igbo to Central Igbo

migrations/20210831163032-add-is-complete-word.js, src/models/Word.js
To better track the status and quality of words within the database, we will add the hidden `isComplete` field on the Word model. This field will only be used within the Igbo API Editor Platform, so we want to make sure our public schema can handle this new field.
=> feat: add isComplete to word model

src/pages/App.js, src/pages/components/Statistics/Statistics.js, tests/cypress/integration/client.test.js
Change the GitHub icon color to match the hover and non-hover states of the button text.
Change Central Igbo to Standard Igbo
=> chore(homepage): change github icon color and central to standard igbo

src/pages/components/Statistics/Statistics.js
This PR uses the regular `img` element instead of Next.js' `Image` component to render remotely hosted images of GitHub contributors
=> fix(site): use HTML img to render GitHub contributors

cypress.json, src/pages/components/Demo/Demo.js, tests/cypress/integration/client.test.js
The Nkọwa okwu link in the demo section wasn't clickable on mobile. There was another element that was sitting on top of the link.
Move the element below the link.
https://twitter.com/codeshifu/status/1470305475560419328?s=20
=> fix(site): make the dictionary link clickable on mobile

migrations/20211218192401-add-isComplete.js, src/models/Word.js
Certain Igbo words will not have tone markings since we have taken the stance of not marking high tones to decrease the tedious nature of editing for translators. To better keep mark when words are fully complete, there is the new `isComplete` field.
=> feat(iscomplete): add the isComplete field to better track word completion

.github/workflows/audio_backup.yml, .github/workflows/dockerize.yml, src/controllers/developers.js
Our SendGrid API token was invalidated, which was throwing an error. But by throwing the error, the successfully created developer token was unable to be sent back to the frontend. This PR catches SendGrid related errors and console logs the message instead of sending back a 400 status code.
This PR also updates a few syntax errors with our CI pipelines.
=> Avoid Throwing Developer Account Creation Error

Dockerfile
The Dockerize action was failing due to using node version 12. This updates the node version to use 16.
=> chore(docker): upgrade docker node version from 12 to 16

package.json
Passing in the `NEXT_PUBLIC_GA_ID` environment variable at build time
=> fix(analytics): pass in the next public ga id during build time

migrations/20220216030851-remove-verb-prefixes.js
To match the lexicographic standard of cataloging Igbo verbs, the Igbo API will migrate its data so that verbs don't include a prefixed hyphen.
=> fix: remove prefixed hyphens from words

src/pages/components/Demo/Demo.js, src/pages/index.js
The Dialects and Examples flags were not returning those data points back to the client side.
=> fix(homepage): fix adding dialects to examples

migrations/20220301211505-convert-unix-to-iso.js, src/controllers/utils/buildDocs.js, src/models/Developer.js, src/models/Example.js, src/models/Word.js, src/models/plugins/index.js, tests/shared/constants.js
The `updatedOn` key was using both Unix and ISO time formats which was causing issues for typed languages. The `updatedOn` field will now be replaced with the `updatedAt` field and it will be using the string ISO format.
Closes #440
=> fix(timestamps): change updatedOn to updatedAt and using ISO format

src/pages/components/Demo/Demo.js
https://user-images.githubusercontent.com/48206628/156936568-ee3d57f0-776c-46ef-8c30-74f7584b3eda.mp4
https://i.imgur.com/mXBpTdE.png
in chrome this is seemingly set automatically, but in firefox we have to explicitly state it, using tailwinds `overflow-auto`
=> fix(site): make demo response scrollable

migrations/20220308132126-add-is-accented.js, src/controllers/utils/buildDocs.js, src/models/Word.js, tests/shared/constants.js
To better track the words that don't require visible accent marks but should still be labeled as accented, the new `isAccented` field will be applied to Word documents.
=> feat(word): migrate word schema to support isAccented

src/controllers/stats.js, src/controllers/utils/index.js, src/controllers/utils/queries.js, src/controllers/words.js, src/pages/components/Statistics/Statistics.js, swagger.json, tests/api-mongo.test.js
To enable filtering through word results, the Igbo API now supports filtering word results through three new queries: `isStandardIgbo`, `nsibidi`, and `pronunciation`.
The Igbo API homepage now shows Nsịbịdị word count.
=> New Word Search Query Params

.github/CONTRIBUTING.md, README.md, src/middleware/analytics.js, src/pages/about.js, src/pages/components/Footer/Footer.js, src/public/locales/ig/about.json, src/siteConstants.js
Now that the Igbo API lives under the `nkowaokwu` organization, all links will need to be updated that originally pointed to the `ijemmao` account.
=> refactor: change ijemmao to nkowaokwu org

migrations/20220423222134-add-attributes.js, src/controllers/utils/buildDocs.js, src/controllers/utils/queries.js, src/controllers/words.js, src/models/Word.js, src/shared/constants/WordAttributes.js, swagger.json, tests/api-mongo.test.js, tests/shared/constants.js
The word model will now support the new field `attributes` which will replace the top-level `isComplete`, `isAccented`, and `isStandardIgbo` fields. These fields will now live inside the new `attributes` field.
This PR also introduces the new nested `attribute` fields `isSlang` for words that are considered to be slang and `isConstructedTerm` for newly formed Igbo words.
=> Support word `attributes` field

migrations/20220425130741-extend-example-sentences-with-style-and-meaning.js, src/models/Example.js, src/shared/constants/ExampleStyles.js, tests/shared/constants.js
This PR introduces two new fields to the Example model: `meaning` and `style`.
* `meaning` is a secondary field for English translation. This field should be used to describe the meaning of a sentence if the literal translation, which would live in the `english` field, isn't clear enough
* `style` is a field to start labeling sentences.
=> Expand Example Sentences

package.json
Use `cross-env` to set `NEXT_PUBLIC_GA_ID` for Windows machines.
=> fix: use cross-env to set NEXT_PUBLIC_GA_ID

.gitignore, db/.gitignore
The `db` directory is now included in the project to allow Windows users to avoid the `NonExistentPath` error that gets thrown by MongoDB when it can't find the `db` directory out-of-the-box.
=> chore: include db directory but exclude contents

src/controllers/stats.js, src/controllers/utils/queries.js, src/pages/components/Statistics/Statistics.js, src/public/locales/en/common.json, src/public/locales/ig/common.json
The Igbo API homepage will now show the total number of developers that have registered for an Igbo API token
.
=> feat(homepage): show developers count stat on the homepage

migrations/20220808024209-add-borrowed-term-field.js, src/controllers/utils/buildDocs.js, src/shared/constants/WordAttributes.js, swagger.json
To provide more nuance to words, word documents will now have the new `isBorrowedTerm` attribute. This PR performs a MongoDB migration to add the new field.
=> feat: add the `isBorrowedTerm` attribute for words

migrations/20220808033804-add-tags.js, src/models/Word.js, src/shared/constants/WordTags.js
To encourage better filtering and searching for users, there will be a new `tags` field that will live on each word document. This PR migrates the MongoDB.
=> feat: add tags for words

src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/utils/queries.js, src/controllers/words.js, src/models/Word.js, src/shared/constants/diacriticCodes.js, src/shared/utils/createRegExp.js, tests/api-mongo.test.js, tests/parse.test.js
Using the MongoDB `$text` index wasn't handling cases where we wanted to have case insensitive and diacritics insensitive search results. To get around this issue, we are now using a custom query that specifies word document fields that should be used to match regex.
=> fix(search): normalize string using NFD and create custom query for individual fields

src/controllers/utils/buildDocs.js, swagger.json, tests/api-mongo.test.js, tests/shared/constants.js
We have been applying verb conjugations or tenses to words that are active, passive, or medial verbs. this PR releases those changes to the public.
=> feat(tenses): release verb tenses

src/controllers/utils/buildDocs.js, src/controllers/utils/index.js
Use aggregation pipelines to count the total number of word documents instead of Mongoose's `countDocuments`
=> fix: count words with aggregate pipeline

src/controllers/utils/buildDocs.js, src/middleware/analytics.js, src/pages/components/Statistics/Statistics.js, src/services/words.js, src/shared/utils/createRegExp.js, tests/api-json.test.js, tests/api-mongo.test.js
Updates search functionality so that:
* User inputted search words are matching with definitions as whole words
* Plural and present continuous (-ing) search terms match with their stems
* Matched documents are sorted in descending order based on the definition to ensure the best definition match appears at the top
* [Why can't I use accented characters next to a word boundary?](https://stackoverflow.com/questions/2449779/why-cant-i-use-accented-characters-next-to-a-word-boundary)
* [Finding words in plural and singular when searching for plural word form in MongoDB](https://stackoverflow.com/questions/51321053/finding-words-in-plural-and-singular-when-searching-for-plural-word-form-in-mong)
=> fix(search): pattern match whole words and sort words by definitions

migrations/20221014123241-add-is-stem.js
There is now a new `attributes.isStem` field available for all word documents
=> feat(is-stem): add the is-stem attribute

src/controllers/utils/buildDocs.js
Instead of `dialects` using their language codes, dialects will now have their resolved values and return their true dialectal name.
=> feat(dialects): resolve dialects

src/controllers/words.js
The Redis cache would save responses if the search word, skip value, and limit value existed collectively as a key. However, this wouldn't take into consideration the case where dialects and examples should be included in the response body.
This PR fixes this issue by including the boolean values for dialects and examples to determine if the response body should come from the cache or from MongoDB.
=> fix(redis): save responses for dialects and examples

src/controllers/utils/buildDocs.js, tests/api-mongo.test.js
Now that we rely mostly on the `createRegExp` helper function to find matching word documents, we can remove the now unnecessary `collation` and `sort` steps.
=> fix(performance): remove sorting and collation step

src/shared/constants/Dialects.js
This PR splits up the Owere and Isuama dialects from one another to best showcase the differences between the two dialects.
=> feat(dialects): split owere and isuama

__tests__/api-mongo.test.js, __tests__/examples.test.js, __tests__/shared/commands.js, __tests__/shared/constants.js, __tests__/shared/utils.js, migrations/20221030034746-restructure-definitions.js, migrations/20221030054330-connect-example-associated-definitions.js, package.json, src/app.js, src/controllers/examples.js, src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/utils/queries.js, src/controllers/words.js, src/dictionaries/seed.js, src/models/Example.js, src/models/Word.js, src/routers/index.js, src/routers/routerV2.js, src/shared/constants/Versions.js, src/shared/constants/sortingDirections.js
This PR introduces a new version of the Igbo API - version 2
In v1, the `definitions` field was an array of strings for definitions. With this new API structure, `definitions` will be an array of objects that will contain both `wordClass` and `definitions`. This enables a given word to be able to support multiple parts of speech rather than just one. This means that there will no longer be a top-level `wordClass` field for each document, that information will be nested within `definitions`.
=> Igbo API v2

__tests__/api-mongo.test.js, migrations/20221107022314-resturcture-dialects-as-arrays.js, src/controllers/utils/buildDocs.js, src/controllers/utils/queries.js, src/dictionaries/seed.js, src/models/Word.js
The `dialects` field will now be an array of objects for version 2 and a deeply nested object for version 1.
=> feat(dialects): refactor dialects to be array of objects

src/controllers/utils/queries.js
The stats section has been broken, rendering only zeroes.
=> fix(stats): check if pronunciation is string before quering

.github/workflows/integration.yml, .github/workflows/lint.yml, package.json
Let's speed up the run time for running tests for the Igbo API by only running tests against Node v16
=> fix(package): use one node version

src/controllers/utils/buildDocs.js
Allow consumers for both v1 and v2 to have access to `attributes.isConstructedTerm`
=> feat(attributes): release constructed terms

migrations/20221124200346-expand-headword.js, src/models/Word.js
Expand the `headword` into `wordPronunciation` and `conceptualWord` to avoid overloading the `headword`
=> feat(headword): add support for expanded headword fields

src/models/Word.js
The Igbo API will now support a new field called `igboDefinitions`
=> feat(definitions): add support for igbo definitions

__tests__/api-mongo.test.js, __tests__/examples.test.js, __tests__/shared/constants.js, migrations/20221217204603-definitions-with-nsibidi.js, src/controllers/examples.js, src/controllers/utils/buildDocs.js, src/controllers/utils/expandVerb.js, src/controllers/utils/index.js, src/controllers/utils/queries.js, src/controllers/words.js, src/middleware/attachRedisClient.js, src/models/Word.js, src/routers/router.js, src/routers/routerV2.js, src/shared/constants/Dialects.js, src/shared/constants/diacriticCodes.js, src/shared/utils/createRegExp.js, src/shared/utils/removeAccents.js
This PR addresses the following:
* `nsibidi` is now placed in `definitions` to allow for multiple Nsịbịdị entries to exists on a word document entry
* Four new dialects have been added: Amaifeke, Ihuoma, Achalla, and Anam
* Search for example sentences has been fixed
=> Support Multiple Nsịbịdị

Dockerfile
Fixes the `dockerize.yml` GitHub Action by avoiding copying the now non-existent `yarn.lock` file
=> chore: stop copying yarn.lock file

.eslintrc.json, src/controllers/examples.js, src/controllers/words.js
The Igbo API was generated twice the amount of necessary Redis caching keys. This cuts this total number in half by placing the Content-Length within the same body of words or examples in the cache.
=> fix(redis): cut number of redis keys in half

package.json, src/middleware/analytics.js, src/shared/constants/diacriticCodes.js
Despite the dataset including the word "secretary" as "òdeākwụ̄kwọ̄", when searched with "ọdeakwụkwọ", the word wouldn't be returned. This was happening because in order for the word to match, it needed the underdot of the first o to be present. However, that's too restrictive for many searches and could apply to hundreds of other word searches.
This PR loosens the search so that it doesn't require an underdot to be present in order to match with the word.
Additionally, this PR removes unnecessary analytics logs along with adding a predev step to help clear out port 8080
=> Conditionally Check Underdots

src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/words.js
The API was sorting the ten random documents that were returned from our DB query instead of sorting all words and then return the ten specified word entires from the sorted words.
=> fix: sort through all words before returning the specified range

.github/workflows/release.yml
Bump `semantic-released` Node version to 18 so that the GitHub Actions Release action works as expected.
Semantic Release Node requirement specification: https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md
=> chore: fix semantic release by bumping node to v18

package.json
The `predev` script will set the Firebase environment to "development"
=> chore: set development environment when running yarn dev

src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/words.js, src/shared/utils/createRegExp.js
The `sortByDocs` function is updated that it now sorts words based on the position in which the `searchWord` appears in the word's first definition.
=> fix: use index of search word in definitions to improve sorting relevancy

migrations/20230118013604-convert-stems-to-object-id.js, src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/words.js, src/dictionaries/seed.js, src/models/Word.js
Allow the `resolve` query to be passed into v2 endpoints to be able to resolve first-level nested `stems` and `relatedTerms`. This PR also performs a database migration to convert all our `stems` values from strings to ObjectIds
=> feat: allow for stems and relatedTerms to be resolved

src/controllers/utils/index.js, src/routers/routerV2.js
Express `res.set` has been updated to allow for both caching and preserving the response cache range header
=> fix: avoid overwriting content-range response header

src/controllers/utils/queries.js, src/models/Word.js
Our search query uses the `$or` operator which splits up each query piece, requiring individual indexes. This PR creates individual indexes to improve search performance
=> fix: add individual indexes for  aggregation operator

.github/workflows/deploy.yml, .github/workflows/dockerize.yml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/release.yml, __tests__/api-mongo.test.js, package.json, src/controllers/utils/index.js, src/controllers/utils/queries.js, src/controllers/utils/searchWordUsingEnglish.js, src/controllers/utils/searchWordUsingIgbo.js, src/controllers/words.js, src/models/Word.js, src/shared/constants/diacriticCodes.js
The ratio of scanned documents to requests was 10,000 which is way too high and would lead to massive performance hits to the API. This was such a big performance hit that MongoDB actually started firing triggered alerts within Atlas warning us about the high memory usage. This PR addresses this performance bottleneck breaking up our database queries.
Individual indexes have been created for fields within the `Word` schema so MongoDB can pick and choose which index it needs to perform the most optimal search. Additionally, the `definitions.definitions` field now uses a text index so that it can find matching Word documents when using English even faster than before.
When a user searches for a word, two separate database queries are started at the same time so that there are two smaller …
=> fix: separate querying database for Igbo words and English words for improved performance

Dockerfile, src/controllers/utils/buildDocs.js
Adds log to get better insight in how long it takes for documents to be retrieved from MongoDB alongside fixing the Dockerize GitHub Actions workflow by using Node v18 instead of v16
=> chore: fix dockerize actions file and log aggregation pipeline for words

jest.config.js, src/APIs/FlagsAPI.js, src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/words.js
This PR caches a leaner version of all verbs and suffixes that doesn't require resolving `examples`, `relatedTerms`, and `stems`
=> fix: caches lean versions of verbs and suffixes to increase caching performance

src/controllers/utils/queries.js
Removed the `generateMultipleWordClass` portion of the word search query to expand the flexibility of search results.
=> fix: remove word class portion of query to expand search

__tests__/shared/constants.js, src/APIs/FlagsAPI.js, src/controllers/utils/buildDocs.js, src/controllers/utils/index.js, src/controllers/utils/searchWordUsingEnglish.js, src/controllers/utils/searchWordUsingIgbo.js
This PR adds support for filtering by `tags` for version 2 of the Igbo API. The expected shape of the `tags` param is a stringified array of valid [`WordTags`](https://github.com/nkowaokwu/igbo_api/blob/master/src/shared/constants/WordTags.js) values.
=> feat(tags): support filtering by `tags` in v2

src/controllers/utils/searchWordUsingIgbo.js
Duplicate word entries were getting returned when a request that had `searchWord === ''` and filters applied was made. This PR fixes this bug by first checking to see if there's a truthy value for `searchWord`. If `searchWord` is truthy, then we will concatenate both Igbo and English word results. If `searchWord` is falsey, then we will just use the Igbo word results.
=> fix(filters): prevent word duplicates while filtering

README.md, migrations/20230314160556-convert-frequency-to-number.js, src/shared/constants/WordAttributes.js
this can be the first step in an effort towards deprecating isCommon
=> feat(attributes): use frequency alongside isCommon

__tests__/api-mongo.test.js, src/APIs/FlagsAPI.js, src/controllers/utils/index.js, src/controllers/utils/queries.js, src/controllers/utils/searchWordUsingEnglish.js, src/controllers/utils/searchWordUsingIgbo.js, src/controllers/words.js, swagger.json
The filtering functionality has been incredibly slow. Load times can be as high as 30 seconds when attempting to filter without any `keyword` value.
This PR changes the MongoDB search queries so that it uses the filtering options `tags` and `wordClasses` to take advantage of the DB indexes to improve search performance.
=> fix: improve filtering performance

src/controllers/utils/index.js
Updates the sorting algorithm so that it will use the words similarity score generated by the `string-similarity` package. Additionally, the variables `prevDocNsibidiFactor` and `nextDocNsibidiFactor` have been renamed to `prevDocIsCommonFactor` and `nextDocIsCommonFactor` since they use the `isCommon` word attribute instead of Nsịbịdị.
Thanks to @anukem for bringing attention to the fact that when a user searches with the keyword "maa" the first-word result is "gbu"
=> fix(sort): rely on word similaries to improve search accuracy

src/middleware/analytics.js
Production Igbo API wasn't sending analytics to Google. This PR changes the `isProduction` value to ensure that when the Igbo API is in production, it's sending analytics to Google.
=> fix: change is production logic for tracking analytics

src/shared/constants/diacriticCodes.js
When users search for words that have a diacritic mark above the letter "m", the associated word doesn't appear. The screenshots below show word entries that exist in our database but aren't discoverable when searched with Igbo.
The RegExp that's generated for all search words will not create an array of optional "m" letters that include diacritic marks. This will expand the search and properly pattern match with these words.
=> fix: support diacritics for the letter m

src/shared/constants/ExampleStyles.js
We want to start supporting sentences from the Bible. The `ExampleStyles.js` file will be extended to support the new sentence style.
=> feat: extend ExampleStyles to include biblical

src/controllers/developers.js, src/middleware/validateApiKey.js, src/models/Developer.js
Applies an index onto the Developer `apiKey` field. Additionally, the API will first use the index to find the developer. If there is no developer returned, then it will scan the entire Developer collection. If it finds a developer, it will update the document's `apiKey` to save the API token to be able to use the index the next time.
N/A
Developers were experiencing 8+ second response times for each of their requests.
Locally on my machine with automated tests.
N/A
=> Io/save developer API tokens

theme.config.jsx
I removed the custom project icon "NG". If the icon is missing, it will be a [GitHub icon](https://primer.style/octicons/mark-github-16) by default.
closes #622 
Clicking on the NG icons leads to the project's GitHub repo, the NG icon does not illustrate such behavior
https://github.com/nkowaokwu/igbo_api/issues/622
I removed the project custom icon, then ran `yarn dev:site` to start front end site for the API. I saw the NG icon was replaced with the GitHub icon
=> fix: remove project icon "NG" and use default icon

src/pages/docs/getting-started.mdx, src/pages/docs/routes/examples.mdx, src/pages/docs/routes/words.mdx
The documentation didn't mention that the `X-API-Header` is required. This PR mentions that requirement.
N/A
The documentation wasn't entirely clear on what's required for the server to work as expected
=> chore(docs): mention that X-API-Header is required

.github/workflows/lint.yml, __tests__/examples.test.js, __tests__/shared/commands.js, __tests__/shared/constants.js, migrations/20230118013604-convert-stems-to-object-id.js, migrations/20230221011130-pronunciation-to-pronunciations.js, migrations/20230522011130-pronunciation-to-pronunciations.js, src/controllers/__tests__/examples.test.js, src/controllers/examples.js, src/controllers/utils/buildDocs.js, src/models/Example.js, src/routers/routerV2.js
A migration script to replace the `pronunciation` field with the new `pronunciations` field to support multiple audio recordings for each example sentence.
N/A
We want to collect a larger variety of data. In order to do this, we want to be able to support multiple audio recordings for each example sentence.
Locally ran the migration step to confirm the script will migrate all the data.
=> Support multiple `pronunciations` in Examples

.github/workflows/deploy.yml, migrations/20230526231511-example-suggestions-approvals-denials-review.js
Migrates the ExampleSuggestion model in the Igbo API database to support `approvals`, `denials`, and `review`
N/A
Allow the Igbo API Editor Platform to approve and deny specific example suggestion audio pronunciations.
Locally migrating the database
N/A
=> chore: migrate example suggestions to support approvals, denials, and review

migrate-mongo-config.js, migrations/20230605005447-trim-headword-and-tenses-whitespace.js, src/models/Word.js
Creates migration pipeline to trim whitespace specifically for headwords and tenses. Additionally, the `trim` field is added to the Mongoose Word model to prevent new documents having whitespace.
N/A
There's quite a few headwords and tenses in our database that have whitespace that is interfering with our search algorithm. 
Locally on my machine.
N/A
=> chore: trim white space throughout word documents

functions/package.json, package.json
Moves Babel and Typescript `devDependencies` to `dependencies`
N/A
Our deploy pipeline has been blocked for two weeks 😱 
Locally
N/A
=> chore: include @babel preset in dependencies

.eslintrc.js, package.json
Installed the prettier library and updated the lint-staged script to first run the prettier command to format the file before linting. Also updated the extends field in .eslintrc.js file adding the eslint-config-prettier plugin as the last plugin in the array to override configurations from other plugins and removed three eslint rules that conflict with prettier. The removed rules where detected using the eslint-config-prettier CLI. Added support for Typescript files
chore #633
Currently, developers need to manually format all their changed files to pass the linting GitHub action #633
Tested the functionality manually, by committing an unformatted file
=> Add prettier support to the project

package.json
Introduces new `package.json` build-related scripts to generate directories that are needed to complete the `build` script.
N/A
Many Windows Users were unable to build the project because a directory wasn't existing while `yarn build` was running.
Locally
N/A
=> Fix `yarn build` for Windows Users

README.md, package.json, scripts/build_src.sh
Introduce the `build_src.sh` bash script to successfully `babel`
N/A
Windows users have been unable to successfully build the project when running `yarn build`. 
Locally and manually
N/A
=> chore: allow Windows machines to build the project fully

src/controllers/utils/buildDocs.ts, src/controllers/utils/minimizeWords.js, src/controllers/utils/queries.js, src/controllers/utils/searchWordUsingIgbo.ts
Adds more logging details to debug production bugs
N/A
Currently, there's a bug within GCP stating that our RegExps are too large, however, we don't know why we're hitting that limit. This PR is the first step in us understanding why the error is getting thrown and how we can fix it.
Locally on my machine. No new tests.
N/A
=> chore: log query builders to understand regex size limit

src/pages/docs/getting-started.mdx, src/pages/docs/routes/examples.mdx, src/pages/docs/routes/words.mdx
Changed the header name for the API key on the docs from `X-API-Header` to `X-API-Key`, which is what the app actually looks for.
Closed #742 
Gives a better and easier experience to future developers that use the docs.
This should not be a breaking change to the application.
=> docs: correct api key header name in docs Fixes #742

@types/is-word.d.ts, package.json, src/controllers/words.ts
Uses the [`is-english`](https://www.npmjs.com/package/is-english) npm package to check whether the search word is in English or not.
N/A
A lot of unrelated words would be returned when simple English terms were searched by users (i.e. apricot, beautiful, thought, etc.) With this change, only relevant word entries will be returned to the user. 
Locally on my machine.
N/A
=> fix: check to see if word is english before searching

src/APIs/FlagsAPI.ts, src/APIs/RedisAPI.ts, src/controllers/utils/buildDocs.ts, src/controllers/utils/expandNoun.ts, src/controllers/utils/expandVerb.ts, src/controllers/utils/index.ts, src/controllers/utils/minimizeVerbsAndSuffixes.ts, src/controllers/utils/minimizeWords.ts, src/controllers/utils/searchWordUsingEnglish.ts, src/controllers/utils/searchWordUsingIgbo.ts, src/controllers/words.ts, src/middleware/analytics.ts, src/middleware/validateApiKey.ts, src/services/database.ts
Stop using console.log in order to reduce total cost of logging within GCP.
=> chore: remove console.log and console.time to reduce logging costs in GCP

.github/CONTRIBUTING.md, .github/workflows/deploy.yml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .npmrc, Dockerfile, README.md, package.json, src/pages/docs/contributing.mdx, src/pages/docs/getting-started.mdx, src/pages/docs/guides/migrating.mdx, src/pages/docs/guides/seeding.mdx, src/pages/docs/guides/testing.mdx
We want to start using `npm` instead of `yarn` since `npm` does a better job at checking package dependencies' versions.
=> Yarn to npm

__tests__/api-json.test.ts, __tests__/api-mongo.test.ts, __tests__/developers.test.ts, __tests__/examples.test.ts, __tests__/homepage.test.ts, __tests__/nsibidi_characters.test.ts, __tests__/parse.test.ts
Hello.
As per the requirement, in order to get rid of the filler word **"should"**, I have completely removed it from the test files.
If at all I misunderstood something or implemented anything incorrectly, then I am extremely sorry.
Kindly let me know if there are any changes required from my end.
Closed #779. 
To get rid of the filler word **"should"** that has been requested in #779.
N/A
N/A
=> Fix #779 : Remove the should prefix from all unit tests titles

src/pages/docs/endpoints/examples.mdx
Made the *style=no_style* into a code block form _`style=no_style`_
This is to close issue #781 
I also noticed that there were extra table columns in that row: standard, proverb, and biblical. They didn't render probably because they only exist on that row. It's what caused the code block problem in the first place. Maybe there's information that was supposed to be in there that was omitted? I'm creating a new issue based on that.
=> Modified the style=no_style so it is in a code block

.github/workflows/integration.yml, migrations/20240928023848-add-languages-to-corpus.js, migrations/20240928024053-add-types-to-projecs.js, src/controllers/utils/buildDocs.ts, src/middleware/helpers/__tests__/authorizeDeveloperUsage.test.ts
We want to add the `languages` field on the `Corpus` and `CorpusSuggestions` models so that we can better understand what text is within each Corpus. Additionally, we want to support multiple types of projects, so a new `types` field will live on the `Projects` model.
Finally, the `projectId` field was leaking into API responses for Example sentences, so this PR omits `projectId` only to include information relevant to the requester.
=> Migrate `Copora` and `Projects` + Omit `projectId`

.github/workflows/integration.yml, src/__tests__/shared/fixtures.ts, src/controllers/__tests__/translation.test.ts, src/controllers/speechToText.ts, src/controllers/translation.ts, src/functions/__tests__/functions.test.ts, src/pages/components/Demo/components/Translate.tsx, src/pages/components/Navbar/__tests__/NavigationMenu.test.tsx, src/pages/components/Navbar/__tests__/NavigationOptions.test.tsx, src/pages/dashboard/__tests__/profile.test.tsx
Fix error in POST requests by sending status code and stringified JSON.
=> fix: send error response and proper json in ai post requests

src/controllers/translation.ts, src/pages/APIs/PredictionAPI.ts, src/pages/components/UseCases/UseCaseCard.tsx, src/pages/shared/useCases.ts
Fix the translation endpoint for the Igbo API.
It is currently returning `transcription: <translation>` instead of `translation: <translation>`. This is likely causing typescript error that bubble up in prod but not locally.
This PR also fixes some other TS errors caused by importing `As` from `@chakra-ui/react`
=> Correct Translation endpoint response key

migrations/20241203060241-insert-owner-firebase-id-on-project.js, migrations/20241203060300-connect-paywall-to-project.js, src/controllers/__tests__/speechToText.test.ts
We have a new collection called `Paywall` that tracks the limits applied to certain users on [Sabbi](https://dashboard.sabbidata.com). A migration script has been created to create `Paywall` documents for each project currently existing in Sabbi. Additionally, we want to track the owning user on the `Project` collection, so another migration script is created to add `ownerFirebaseId` on the `Project` collection.
=> Introduce Paywalls and add ownerFirebaseId on Projects

migrations/20241206235108-remove-crowdsourcing.js
Introduces a migration script to remove the unused `crowdsourcing` field on `WordSuggestions` and `ExampleSuggestions`.
=> fix: removes `crowdsourcing` field on `wordsuggesitons` anad `examplesuggestions` collection
