README.md
controllers/words.js
server.js
services/words.js

Developers can now interact with the API to grab information about an Igbo term by following the route structure described in the README.

Search Dictionary

---

.github/workflows/integration.yml
controllers/words.js
package.json
server.js
tests/api.test.js
utils/constants/errorMessages.js
yarn.lock

Introduces new tests along with a CI pipeline
Address #5

Continuous integration

---

utils/normalization.js

Change for loop to reduce

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md

A new CONTRIBUTION.md and CODE_OF_CONDUCT.md guides to encourage open-source collaboration.

Create contribution and code of conduct guide

---

README.md

This update in the README will help more people get onboarded onto cloning and running this project.

Create a Getting Started section

---

README.md

added try it out section

---

src/controllers/phrases.js
src/controllers/words.js
src/dictionaries/seed.js
src/dictionaries/utils/writeToFiles.js
src/shared/constants/populateDocuments.js
src/shared/utils/createRegExp.js
tests/api-mongo.test.js
tests/shared/commands.js
yarn.lock

When a user searches for a phrase, the word object that holds that phrase (a `parentWord`) will be returned.
Closes #10

Search phrases

---

README.md
src/controllers/words.js
tests/api-mongo.test.js
tests/shared/commands.js

Developers can now paginate through large responses by using the `page` query.
Closes #84

Pagination

---

src/dictionaries/seed.js

Return save promises so they can all be resolved at the same time.

Update seed function

---

.github/workflows/gatsby-integration.yml
cypress.json
cypress/fixtures/example.json
cypress/integration/home.spec.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
package.json
src/pages/index.js
yarn.lock

Added two Cypress tests for the front site.
Closes #98

Cypress Testing

---

.gitignore
package.json
src/server.js
yarn.lock

Once deployed to production, anyone from anywhere can request data from the API without having to use [CORS Anywhere](https://cors-anywhere.herokuapp.com/)

Handle cors

---

.eslintrc.json
src/components/Example.js
src/components/Phrase.js
src/components/Word.js
src/utils/PropTypeShapes.js

Define prop type shapes

---

README.md
src/routers/index.js
src/routers/router.js
src/server.js
tests/shared/commands.js
tests/shared/constants.js

This PR removes the use of the `search` path in the API route.

Igbo api 141/restructure api

---

src/controllers/exampleSuggestions.js
src/controllers/examples.js
src/controllers/wordSuggestions.js
src/controllers/words.js
src/models/Example.js
src/routers/editRouter.js
src/routers/router.js
tests/__mocks__/documentData.js
tests/api-mongo.test.js
tests/exampleSuggestions.test.js
tests/examples.test.js
tests/shared/commands.js
tests/wordSuggestions.test.js

`Word` and `Example` documents can be updated using the new routes:
* `api/v1/words/:id`
* `api/v1/examples/:id`
Closes #123

Igbo api 123/put words examples

---

src/controllers/exampleSuggestions.js
src/controllers/examples.js
src/controllers/genericWords.js
src/controllers/utils/index.js
src/controllers/wordSuggestions.js
src/controllers/words.js
tests/api-mongo.test.js
tests/exampleSuggestions.test.js
tests/examples.test.js
tests/genericWords.test.js
tests/shared/utils.js
tests/wordSuggestions.test.js

Handles the `sort` query that's defined by [`react-admin`'s data providers `sort` query](https://marmelab.com/react-admin/DataProviders.html)
Closes #143

Igbo api 143/sort query

---

.github/workflows/backup.yml
.gitignore
scripts/sync.sh

An automated solution to backing up the production databse

Create script to backup production data

---

.github/workflows/backup.yml
scripts/sync.sh

It seems like the compressed files are getting truncated. This PR fixes that

Fix script to backup production data

---

src/routers/editorRouter.js
src/routers/index.js
src/routers/router.js
src/server.js
tests/shared/commands.js
tests/shared/constants.js

This removes the concept of the `api/v1/edit/**` and shortens it to `api/v1/`

Restructure API endpoints

---

src/controllers/utils/index.js
tests/api-mongo.test.js
tests/exampleSuggestions.test.js
tests/examples.test.js
tests/genericWords.test.js
tests/wordSuggestions.test.js

Igbo api 163/Handle filter query

---

src/shared/constants/diacriticCodes.js
src/shared/utils/createRegExp.js
tests/api-mongo.test.js

This PR makes the search case-insensitive
Closes #171

Make Regex case insensitive

---

src/pages/App.js
src/pages/components/Demo/Demo.js
src/pages/components/Navbar/Navbar.js
src/pages/styles.css

The homepage content is now taking up the entire width of a mobile screen.
Closes #189

Use entire mobile width

---

src/pages/components/Demo/Demo.js
src/pages/styles.css
tests/api-mongo.test.js

This fixes the responsive bugs for the API Homepage

Change responsive implementation

---

.eslintrc.json
cypress/integration/home.spec.js
cypress/support/commands.js
package.json
src/pages/index.js
yarn.lock

There's now a pagination bar at the bottom of results to make it easier for users to see all words.

Igbo api 174/render pagination

---

cypress/integration/home.spec.js
cypress/support/commands.js
src/assets/icons/search.svg
src/components/Navbar.js
src/pages/about.js
src/pages/index.js

This PR does the following:
* Adds a short About page
* Updates the search bar to remove the green search button
* Adds a Navbar component for navigation
Closes #172

Add About page and navbar

---

gatsby-config.js
package.json

Allows for deploying to [https://nkowaokwu.com](https://nkowaokwu.com)

Remove path prefixes

---

src/components/Navbar.js
src/pages/index.js
src/styles/tailwind.css
tailwind.config.js

This PR addresses the issue where the column of results get squished on smaller screens that aren't necessarily mobile devices.

Fix spacing of all words

---

src/forms/AddExample.js
src/forms/AddWord.js
src/styles/tailwind.css

Moves out the styles variables out from JS and into CSS.
Closes #222

Remove style variables in JS

---

src/controllers/exampleSuggestions.js
src/controllers/genericWords.js
src/controllers/wordSuggestions.js
src/middleware/authorization.js
src/routers/editorRouter.js
swagger.json
tests/exampleSuggestions.test.js
tests/genericWords.test.js
tests/shared/commands.js
tests/wordSuggestions.test.js

Creates new DELETE routes for `WordSuggestion`, `ExampleSuggestion`, and `GenericWord` documents.
Closes #167 
Closes #168

Igbo api 167/delete word and example suggestions

---

package.json

Retrying flaky failing tests will help increase confidence in the current testing suite.
Closes #242

Retry failing tests up to three times

---

src/controllers/exampleSuggestions.js
src/controllers/genericWords.js
src/controllers/wordSuggestions.js
yarn.lock

Refactors the code so that the Mongoose "find" functional changes are abstracted to a new function for each document type.
Close #251

Refactor find functions

---

.github/workflows/integration.yml
migrations/20201118192335-add-merged-by.js
src/config.js
src/controllers/examples.js
src/controllers/users.js
src/controllers/utils/index.js
src/controllers/words.js
src/middleware/authentication.js
src/models/ExampleSuggestion.js
src/models/GenericWord.js
src/models/WordSuggestion.js
src/routers/adminRouter.js
src/shared/constants/testAuthTokens.js
tests/api-json.test.js
tests/api-mongo.test.js
tests/auth.test.js
tests/editing-flow.test.js
tests/exampleSuggestions.test.js
tests/examples.test.js
tests/shared/commands.js
tests/shared/constants.js
tests/users.test.js

* There is a new `mergedBy` key that lives on all `wordSuggestion`, `exampleSuggestion`, and `genericWord` documents
* This will help keep track of who merged the document into a real word or example document
* Update the auth middlware
* Relies on the `FIREBASE_CONFIG` environment variable to use Firebase Admin SDK
* Provides all Firebase users to admins
* Adds tests

mergedBy Fields and Update Auth Middleware

---

src/config.js
src/pages/App.js
src/pages/about.js
src/pages/components/Navbar/Navbar.js
tests/api-mongo.test.js
tests/homepage.test.js
tests/shared/commands.js
tests/shared/constants.js
yarn.lock

Multi-page sites aren't supported when served through the API. Because of this, the About page is unable to get served to the client. To get around this, there is now a footer section that will render contact information.

Move about page

---

src/server.js
swagger.json
tests/genericWords.test.js

Removes the production guardrails for hiding the new editor and admin routes 🎉
This allows for the editor platform to make the necessary network requests to edit the database.

Remove guardrails and update docs

---

migrations/20201121195224-add-updated-on-for-words-and-examples.js
src/controllers/exampleSuggestions.js
src/controllers/genericWords.js
src/controllers/users.js
src/controllers/utils/buildDocs.js
src/controllers/utils/index.js
src/controllers/wordSuggestions.js
src/models/Example.js
src/models/Word.js
tests/api-mongo.test.js
tests/examples.test.js
tests/homepage.test.js
tests/shared/constants.js

* Migrates the database for all words, examples, wordSuggestions, exampleSuggestions, and genericWords to have a new `updatedOn` field
* Populates Firebase users on wordSuggestion, exampleSuggestion, and genericWord document
* Updates tests

Last Updated On for words and examples

---

Dockerfile

Change the environment variable from `development` to `test` so the populate database scripts don't exit out with a `0` status code.

Update Dockerfile with proper environment variable

---

.github/workflows/dockerize.yml
package.json
src/config.js
src/controllers/wordSuggestions.js
src/middleware/authentication.js
src/routers/editorRouter.js
yarn.lock

* Updates `dockerize.yml` to handle secret tokens
* Handles stringified body error
* Updates `authentication.js` file to handle reading auth tokens while in a testing environment

Testing updates

---

src/pages/App.js
src/pages/components/Demo/Demo.js
src/pages/components/Navbar/Navbar.js
src/siteConstants.js

The front site went down because of a Firebase environment variable change. This PR should address that bug.

Remove unexpected Firebase env var from the front site

---

src/config.js
src/controllers/email.js
src/pages/App.js
src/siteConstants.js

* Uses the new nkowaokwu@gmail.com email to send emails to uses for the dictionary app

Send emails for Nkowaokwu and Igbo API

---

package.json
src/server.js
yarn.lock

To help with enhancing the speed of results coming from the API, this PR introduces compressing results so that the data can be transferred across a network quicker.

Send compressed assets

---

src/controllers/genericWords.js
src/dictionaries/seed.js

Adding extra console messages to make it clear when the server is about to restart.

Console log restarting server

---

package.json
src/routers/router.js
src/server.js
yarn.lock

Rate limits users to 20 requests per 15 minutes

Rate limit creating developers

---

Dockerfile
src/config.js

Revert "Allow Docker consumers to change NODE_ENV variable"

---

Dockerfile
src/config.js

Revert "Revert "Allow Docker consumers to change NODE_ENV variable""

---

src/shared/constants/wordClass.js

feat: Create Igbo Part of Speech Tagset Constant

---

package.json
src/pages/components/Demo/Demo.js
src/siteConstants.js

Fix incorrect redirect

---

README.md

Add build step

---

package.json
src/middleware/validateDeveloperBody.js
yarn.lock

refactor(issue-360): used joi to validate developer request body

---

src/pages/_app.js

fix: address typo in homepage title

---

package.json
src/controllers/utils/index.js
src/controllers/utils/queries.js
src/controllers/words.js
src/routers/router.js
tests/api-mongo.test.js
tests/shared/commands.js

Resolves #363 Filtering Part of Speech ticket

363 filter with word class

---

.github/workflows/lint.yml
src/controllers/utils/queries.js
src/pages/about.js
src/routers/router.js

Runs ESLint on all pushes to any remote branch. This will help catch any linting errors automatically.

chore: create lint action

---

package.json

Specifying engine versions for npm, node, and yarn

chore(engines): specify node engines

---

src/controllers/developers.js
src/pages/signup.js

Users are able to sign up for developer tokens. This PR doesn't fix this bug, instead, it logs the trace in order to catch the bug

test: log trace

---

src/pages/App.js
src/pages/components/Footer/Footer.js
src/pages/components/Navbar/SubMenu.js
src/siteConstants.js

The homepage had a few broken links, this PR fixes them!

Fix Homepage links

---

migrations/20211121214701-add-nyms.js
src/controllers/utils/buildDocs.js
src/models/Word.js
tests/shared/constants.js

The Igbo API will expand to support the following fields:
* Synonyms
* Antonyms
* Hypernyms
* Hyponyms

feat: support nym fields

---

README.md
src/pages/components/Demo/Demo.js
src/pages/components/MentionedIn/MentionedIn.js
src/pages/index.js
src/styles.css
tests/cypress/integration/client.test.js

The input field within the Try it out section was losing focus after the first character input. This PR fixes this bug.

fix(site): retain focus in demo input

---

src/pages/components/Demo/Demo.js

The site wasn't jumping to the Try it out section after clicking the Submit button.

fix(site): jump to try it out section

---

migrations/20220107155512-add-nsibidi.js
src/controllers/utils/buildDocs.js
src/models/Word.js
src/pages/App.js
src/pages/about.js
src/pages/components/Demo/Demo.js
src/pages/components/MentionedIn/MentionedIn.js
src/pages/components/Navbar/SubMenu.js
src/pages/components/Statistics/Stat.js
src/pages/components/Statistics/Statistics.js
src/styles.css
tests/shared/constants.js

The Igbo API will now support the `nsibidi` field on all word documents through our database migration. The field will be an empty string by default and will be editable on the Igbo API Editor Platform.
This PR also updates a few UI bugs for the homepage.

Support Nsịbịdị

---

src/pages/_app.js
src/pages/components/Input/Input.js
src/pages/gtag.js

Adding Google Analytics to track general activity and traffic on the Igbo API homepage.

chore(google): add google analytics tracking for each page

---

src/models/Word.js

Enables the API to search for words by using Nsịbịdị unicodes

Search by Nsịbịdị

---

src/pages/index.js

Escaping characters to ensure they work on homepage.

fix(nsibidi): escape characters for homepage demo section

---

src/models/Word.js

Changes the way we create text indexes for the Word collection to remove dynamic indexes for dialectal words.

chore(indexes): update the word indexes to support nsibidi text search

---

src/shared/constants/wordClass.js

Adds the new medial verb word word class

feat(wordclass): include the new medial verb word class

---

migrations/20220208140327-example-pronunciations.js
src/models/Example.js
tests/shared/constants.js

Example sentences will now be able to support audio recordings

Add Pronunciation to Examples

---

src/controllers/utils/index.js

This PR improves the word search results by normalizing the search word and MongoDB word documents' words.

refactor: normalize strings while sorting results

---

src/config.js
src/shared/utils/injectWordClass.js
swagger.json

The documentation site will now explain the different types of word classes.

docs: add word class description in docs

---

src/shared/constants/Dialects.js

Adds support for the following dialects:
* Ajalli (Ajali)
* Awkuzu(Okuzu)
* Udi
* Ezeagu
* Changes Ogodi to Ogidi

feat(dialects): add more dialects

---

clean.mjs
src/services/redis.js

fix(redis): use url instead of uri

---

src/shared/constants/WordTags.js

This PR adds all the latest word tags that exist.

feat(tags): extend the word tags

---

src/controllers/utils/index.js
src/pages/components/Demo/Demo.js

The spacing on responsive views was squishing sections together.

fix(site): fix responsive spacing

---

src/shared/constants/Dialects.js

We want to add the following dialects:
* Ezza
* Izii
* Ikwo

feat(dialects): add Ezza,  Izii and Ikwo dialects

---

__tests__/api-json.test.js
__tests__/api-mongo.test.js
__tests__/examples.test.js
__tests__/parse.test.js
__tests__/shared/utils.js
src/app.js
src/controllers/developers.js
src/controllers/email.js
src/controllers/examples.js
src/controllers/stats.js
src/controllers/utils/buildDocs.js
src/controllers/utils/index.js
src/controllers/words.js
src/dictionaries/buildDictionaries.js
src/dictionaries/seed.js
src/middleware/validateApiKey.js
src/models/Developer.js
src/models/Example.js
src/models/Word.js
src/pages/components/Demo/Demo.js
src/routers/siteRouter.js
src/services/database.js
src/services/redis.js
src/services/words.js
src/shared/utils/documentUtils.js
src/shared/utils/normalization.js
src/shared/utils/replaceAbbreviations.js

Create unique Mongoose connections for each request. Additionally, imports only necessary Lodash modules.

fix(memory): create connections for individual requests

---

src/controllers/stats.js

Use `.value` to grab the value for a given stat

fix(stats): use stat values

---

src/shared/constants/Dialects.js

This PR adds support for the new Abiriba dialect

feat(dialect): add supporrt for abiriba dialect

---

__tests__/api-mongo.test.js
src/pages/components/Demo/Demo.js
src/shared/utils/createRegExp.js

Users have been unable to reach certain words like "mmadụ̀" by searching with the keyword "mmadụ" because we weren't normalizing each character with NFD.

fix(search): normalize individual characters with NFD to better match

---

migrations/20221207003231-nominal-modifier.js
src/shared/constants/WordClass.js

The Igbo API will support a new type of part of speech: Nominal Modifier

feat(wordclass): nominal modifier has been added as a new part of speech

---

package.json
src/controllers/utils/expandNoun.js
src/controllers/utils/expandVerb.js
src/controllers/utils/index.js
src/shared/constants/PartTypes.js

This PR will greatly improve the words that are returned when an entire sentence or phrase is provided as the search term. This change only applies to v2.

feat: breakdown phrases to search for individual words

---

src/controllers/utils/expandNoun.js
src/controllers/utils/expandVerb.js
src/controllers/utils/index.js

Logging our expansion functions to monitor production performance.

chore: include timestamps for expansions

---

src/controllers/words.js

Describe which word has a certain `contentLength`

chore: couple search word with content length

---

src/controllers/examples.js
src/controllers/utils/RedisAPI.js
src/controllers/utils/index.js
src/controllers/words.js

Create the new `RedisAPI.js` file to better handle our getters and setters to the Redis instance and to have logs for Redis interactions.

chore(redis): create a dedicated API file to introduce logging

---

src/controllers/utils/buildDocs.js
src/controllers/utils/index.js
src/controllers/words.js

Reverts nkowaokwu/igbo_api#529

Revert "fix: sort through all words before returning the specified range"

---

migrations/20230112035359-add-is-common.js
src/shared/constants/WordAttributes.js

Adding the new attribute `isCommon` to assign word frequency to words.

feat: add new 'isCommon' attribute to words

---

src/controllers/utils/buildDocs.js
src/controllers/utils/index.js

* Releases `isBorrowedTerm` attribute to production.
* Uses `isCommonTerm` to determine word order

feat: Sort results with `isCommonTerm`

---

__tests__/api-mongo.test.js
src/controllers/examples.js
src/controllers/utils/index.js
src/controllers/words.js
src/routers/routerV2.js

Create new top-level `data` and `length` fields for v2

feat: create top level data and length fields

---

src/models/Word.js

Change indexes for `Word` model to improve scanning data

fix: change word model indexes

---

.github/workflows/deploy.yml
.github/workflows/dockerize.yml
.github/workflows/integration.yml
.github/workflows/lint.yml
.github/workflows/release.yml
__tests__/api-mongo.test.js
package.json
src/controllers/utils/index.js
src/controllers/utils/queries.js
src/controllers/utils/searchWordUsingEnglish.js
src/controllers/utils/searchWordUsingIgbo.js
src/controllers/words.js
src/models/Word.js
src/shared/constants/diacriticCodes.js

Reverts nkowaokwu/igbo_api#550

Revert "Revert "fix: separate querying database for Igbo words and English words for improved performance""

---

.github/workflows/release.yml
Dockerfile
__tests__/api-mongo.test.js
package.json
src/config.js
src/controllers/utils/index.js
src/controllers/utils/queries.js
src/controllers/utils/searchWordUsingEnglish.js
src/controllers/utils/searchWordUsingIgbo.js
src/controllers/words.js
src/models/Word.js
src/shared/constants/diacriticCodes.js

Reverts nkowaokwu/igbo_api#552

Revert "Revert "Revert "Revert "fix: separate querying database for Igbo words and English words for improved performance""""

---

.eslintrc.json
src/controllers/stats.js
src/pages/components/Statistics/Statistics.js
src/public/locales/en/common.json
src/public/locales/ig/common.json
src/shared/constants/StatTypes.js

Add the Igbo Definitions stats on the home page.

chore(homepage): add the igbo definitions stats on the homepage

---

src/controllers/utils/index.js

The `IS_COMMON` sort factor would be applied to any word that would appear in the words result list, whether or not it matched closely with the provided search term. This PR fixes this bug by considering the similarity of the common term with the search term to see if the common term should appear at the top of the search results or lower down in the search results.
If a word exactly matches the search term, then a new `EXACT_MATCH_FACTOR` factor is applied to the search term to appear at the top of the search results.

fix(sort): conditionally apply the common term factor while sorting

---

migrations/20230409220217-convert-igbo-definitions-to-include-nsibidi.js
src/models/Example.js
src/models/Word.js
src/models/plugins/index.js

Extend the data shape of `igboDefinitions` to be an array of objects that include the `igbo` and `nsibidi` fields.

feat(words): add `nsibidi` to `igboDefinitions` array

---

README.md

Fixed a typo on the Readme page.

docs: Fixed a typo in the readme

---

src/middleware/analytics.js
src/middleware/validateApiKey.js

Add logging within the middleware to better understand what would be leading to slower response times.

chore: add logging for middleware

---

src/controllers/utils/index.js
src/controllers/utils/searchWordUsingIgbo.js
src/middleware/analytics.js
src/middleware/attachRedisClient.js

Adds more logging to better understand the latency between request and response.

chore: add more logs for monitoring performance

---

src/controllers/utils/index.js
src/controllers/utils/searchWordUsingIgbo.js
src/middleware/analytics.js
src/middleware/attachRedisClient.js

Reverts nkowaokwu/igbo_api#594

Revert "chore: add more logs for monitoring performance"

---

__tests__/api-mongo.test.js
src/controllers/utils/index.js

Reverts nkowaokwu/igbo_api#584

Revert "Io/remove headers"

---

src/models/Example.js
src/shared/constants/SentenceTypes.js

Support the `type` field for Examples

chore(example): add sentence types

---

src/pages/dashboard.js

Create dashboard page
Closes #598

598 create dashboard page

---

__tests__/shared/constants.js
src/controllers/stats.js
src/pages/components/Statistics/Statistics.js
src/public/locales/en/common.json
src/public/locales/ig/common.json
src/shared/constants/StatTypes.js

Show on the homepage how many proverbs are available in the Igbo API.

chore(site): show the proverbs count

---

src/pages/components/Statistics/Statistics.js
src/public/locales/en/common.json
src/public/locales/ig/common.json
src/shared/constants/StatTypes.js

Show the total number of Bible verses are present in the database.

chore(site): add Bible verses to homepage

---

src/pages/_document.js

Add meta data information for better SEO and an image preview
N/A
There's no URL image preview 😱 
Tested locally on my computer
N/A

chore(site): add image preview and other meta tag information

---

src/controllers/stats.js

Fetching the bible verses present within the database
N/A
Currently, the Bible Verses count is set to 0 because we weren't fetching the data.
Locally on my computer
N/A

chore(site): get bible verses count

---

.gitignore
src/pages/dashboard.js
src/pages/login.js
src/pages/privacy.js
src/pages/signup.js

created the login page

---

src/shared/constants/Dialect.ts

Change dialect labels to Igbo spellings rather than English spellings.
N/A
Best to represent our own dialects in the native language.
Locally
N/A

chore: change the dialect labels to Igbo spelling

---

src/pages/App.js

Fix the typo
Closed #665 
@ijemmao review

Fix typo in App.js

---

src/pages/components/Statistics/Statistics.js

Closes #681 
**Issue Description:**
Is your feature request related to a problem? Please describe.
Update our total community size from 150+ to 230+
Describe the solution you'd like
Update our total Slack community size from 150+ to 230+
Describe alternatives you've considered
N/A
Additional context

enhancement: Update Slack community count from 150+ to 230+

---

src/pages/components/Navbar/Navbar.js

made navbar fixed for all devices
closed issue #693
Make the navbar also fixed on mobile devices.

fix: fixed navbar on all devices #693

---

src/pages/about.js

Removed `h-full` Property to Fix the Issue
Closed #696

Fix: Text Overlaping Issue

---

src/controllers/utils/queries.js
src/controllers/utils/searchWordUsingEnglish.ts
src/controllers/utils/searchWordUsingIgbo.ts

Supports case insensitivity searches.
N/A
The search results for "Che" vs "che" weren't the same.
Locally tested
N/A

fix(word): support case insensitive searches

---

src/middleware/analytics.ts
src/middleware/attachRedisClient.ts
src/middleware/cache.ts
src/middleware/errorHandler.ts
src/middleware/logger.ts
src/middleware/validId.ts
src/middleware/validateAdminApiKey.ts
src/middleware/validateApiKey.ts
src/middleware/validateDeveloperBody.ts

- This adds the correct type for arguments in the functions in `src/middleware` files
- This creates new types and interfaces where needed
- This uses the `any` type in few arguments where their type is dependent on files outside this folder or can not be easily determined
Closed #728
Migrating entire project to TypeScript
Locally
N/A

chore: Use the correct argument types in src/middleware files

---

src/controllers/utils/buildDocs.ts
src/controllers/utils/queries.js
src/controllers/utils/sortDocsBy.ts

fix: chore filter out unnecssary words while sorting

---

__tests__/__mocks__/documentData.js
__tests__/auth.test.js
__tests__/developers.test.js
__tests__/shared/commands.js
src/controllers/auth/login.ts
src/controllers/developers.ts
src/controllers/utils/findDeveloper.ts
src/middleware/authorization.js
src/middleware/validateApiKey.ts
src/routers/router.ts

Created the login endpoint and controller
#704

Fix create login endpoint

---

.gitignore
src/APIs/FlagsAPI.ts
src/APIs/RedisAPI.ts
src/controllers/types.ts
src/controllers/utils/index.ts
src/controllers/utils/minimizeWords.ts
src/controllers/utils/queries.ts
src/controllers/utils/searchWordUsingIgbo.ts
src/controllers/utils/types.ts
src/types/word.ts

* Convert top level JS in /controllers/utils to TS
* install relevant type definitions for modules that don't ship their own types
* Create new global and file scoped types where necessary
* Relocated types that are needed by other external modules into the global types module
* Minimal but inevitable refactoring in order to make files strongly typed and also compile, for example, I wrapped this existing code
```TS
// src/controllers/utils/minimizeWords.ts
minimizedDefinition = omit(minimizedDefinition as Partial<Definition>, [
'label',
'igboDefinitions',
'_id',
'id',
]);
if (!minimizedDefinition.nsibidi) {
minimizedDefinition = omit(minimizedDefinition, ['nsibidi']);
}
```
inside a typeof check condition below:
```TS
// src/controllers/utils/minimizeWords.ts
if (typeof definition === …
```

Convert controller util files to typescript

---

cypress/e2e/client.cy.js
src/pages/components/Navbar/NavigationMenu.tsx

Changes/Improvements to cypress test code to cater for new changes causing pipeline failures
Closed #773 
Resolve pipeline failure.
Run `npm run cypress:run`

Fix failing cypress tests

---

migrations/20240908000598-create-default-igbo-api-project.js

Database migration to create a default Project for the Igbo API project.

Create default project for Igbo API

---

src/controllers/__tests__/translation.test.ts
src/controllers/speechToText.ts
src/controllers/translation.ts

Revert changes made to AI endpoint controllers to fix functionality of home page

refactor: revert changes so home page still works
